package com.tesst;
// Generated 2018-2-2 16:05:43 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LovesFansId generated by hbm2java
 */
@Embeddable
public class LovesFansId implements java.io.Serializable {

	private int fans;
	private int fansOrder;

	public LovesFansId() {
	}

	public LovesFansId(int fans, int fansOrder) {
		this.fans = fans;
		this.fansOrder = fansOrder;
	}

	@Column(name = "FANS", nullable = false)
	public int getFans() {
		return this.fans;
	}

	public void setFans(int fans) {
		this.fans = fans;
	}

	@Column(name = "fans_ORDER", nullable = false)
	public int getFansOrder() {
		return this.fansOrder;
	}

	public void setFansOrder(int fansOrder) {
		this.fansOrder = fansOrder;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LovesFansId))
			return false;
		LovesFansId castOther = (LovesFansId) other;

		return (this.getFans() == castOther.getFans()) && (this.getFansOrder() == castOther.getFansOrder());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFans();
		result = 37 * result + this.getFansOrder();
		return result;
	}

}
