package com.tesst;
// Generated 2018-2-2 16:05:43 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Topics generated by hbm2java
 */
@Entity
@Table(name = "topics", catalog = "stonewalls")
public class Topics implements java.io.Serializable {

	private Integer tid;
	private String typename;
	private Integer hotdegree;
	private Set<Posts> postses = new HashSet<Posts>(0);

	public Topics() {
	}

	public Topics(String typename, Integer hotdegree, Set<Posts> postses) {
		this.typename = typename;
		this.hotdegree = hotdegree;
		this.postses = postses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TID", unique = true, nullable = false)
	public Integer getTid() {
		return this.tid;
	}

	public void setTid(Integer tid) {
		this.tid = tid;
	}

	@Column(name = "TYPENAME")
	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	@Column(name = "HOTDEGREE")
	public Integer getHotdegree() {
		return this.hotdegree;
	}

	public void setHotdegree(Integer hotdegree) {
		this.hotdegree = hotdegree;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "topics")
	public Set<Posts> getPostses() {
		return this.postses;
	}

	public void setPostses(Set<Posts> postses) {
		this.postses = postses;
	}

}
